//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETALLE_PEDIDO
    {
        public int DEP_ID { get; set; }
        public Nullable<int> PED_ID { get; set; }
        public Nullable<System.DateTime> PED_FECHA { get; set; }
        public Nullable<int> PRO_ID { get; set; }
        public Nullable<int> DEP_CANTIDAD { get; set; }
        public string DEP_DESCRIPCION { get; set; }
        public Nullable<decimal> DEP_PRECIOUNITARIO { get; set; }
        public Nullable<decimal> DEP_PRECIOTOTAL { get; set; }
        public string DEP_ESTADO { get; set; }
    
        public virtual TBL_PEDIDO TBL_PEDIDO { get; set; }
        public virtual TBL_PRODUCTO TBL_PRODUCTO { get; set; }
    }
}
