//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DIRECCIONES
    {
        public int DIR_ID { get; set; }
        public Nullable<long> CLI_ID { get; set; }
        public Nullable<int> CLI_DNI { get; set; }
        public string DIR_PRIMEARIA { get; set; }
        public string DIR_SECUNDARIA { get; set; }
        public string DIR_NUMERACION { get; set; }
        public string DIR_REFERENCIA { get; set; }
        public string DIR_ESTADO { get; set; }
        public Nullable<System.DateTime> DIR_ADD { get; set; }
        public string DIR_CODIGOPOSTAL { get; set; }
    
        public virtual TBL_CLIENTE TBL_CLIENTE { get; set; }
    }
}
